### ISSUE TITLE
"Schedule meeting" button goes nowhere

### ISSUE THREAD

**Issue by BraydenTW** [hashirshoaeb/portfolio#11] opened 2022-10-26 20:49 UTC
Hey there! When I click the "Schedule meeting" button at the bottom of your site, it goes nowhere.

Just though I would let you know.

**Comment by hashirshoaeb** [comment] 2022-10-27 07:40
Thank you for letting me know. I'm aware of it. I have planned to integrate Calendly link, but not getting enough time for it.

**Comment by hashirshoaeb** [comment] 2022-10-27 07:41
Duplicate of #9 , so closing it.

**Closed by hashirshoaeb** 2022-10-27 07:41 UTC
